version: "3.8"

services:

    nginx:
        image: dsuite/alpine-nginx:latest
        container_name: nginx
        environment:
            - DEBUG_LEVEL=DEBUG
            - NGINX_ROOT=public
            - NGINX_DEBUG=true
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www:ro
            - ./log:/var/log
